# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "w10x64" do |w|
    w.vm.box = "iznav/w10x64"
    # w.vm.hostname = "w10x64"
    w.vm.communicator = "winrm"
    w.vm.guest = "windows"

    w.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.name = "w10x64_generic"
      vb.customize ["modifyvm", :id, "--memory", 2048]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--vram", "256"]
    end

    w.vm.provision "file", source: "scripts/add_kbd_layout.xml", destination: "$Env:TEMP\\add_kbd_layout.xml"

    w.vm.provision "shell", path: "scripts/chocolatey.cmd"
    w.vm.provision "shell", path: "scripts/choco_packages.cmd"
    w.vm.provision "shell", path: "scripts/pip_packages.cmd"
    w.vm.provision "shell", path: "scripts/timezone.cmd"
    w.vm.provision "shell", path: "scripts/keymap.cmd"
    w.vm.provision "shell", path: "scripts/disable_ipv6.cmd"
    # w.vm.provision "shell", path: "scripts/change_dns.cmd"
  end
end
