# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "default" do |w|
    w.vm.box = "iznav/w10x64"
    w.vm.hostname = "w10x64"
    w.vm.communicator = "winrm"
    w.vm.guest = "windows"

    w.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.name = "w10x64_generic"
      vb.customize ["modifyvm", :id, "--memory", 2048]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--vram", "256"]
      vb.customize ["setextradata", "global", "GUI/MaxGuestResolution", "any"]
      vb.customize ["setextradata", :id, "CustomVideoMode1", "1024x768x32"]
    end
  end
end
