# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "iznav/w10x64"
  config.vm.hostname = "w10x64"
  config.vm.communicator = "winrm"
  config.vm.guest = :windows

  config.vm.provider :virtualbox do |v, override|
    v.gui = true
    v.name = "w10x64_generic"
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--cpus", 2]
    v.customize ["modifyvm", :id, "--vram", "256"]
    v.customize ["setextradata", "global", "GUI/MaxGuestResolution", "any"]
    v.customize ["setextradata", :id, "CustomVideoMode1", "1024x768x32"]
  end
end
