# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "bento/ubuntu-18.04"
    ubuntu.vm.hostname = "ubuntu"

    ubuntu.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu"
      vb.gui = false
      vb.memory = 1024
      vb.cpus = 2
    end

    ubuntu.vm.provision "shell", path: "sh/update.sh"
    ubuntu.vm.provision "shell", path: "sh/console.sh"
    ubuntu.vm.provision "shell", path: "sh/virtualbox.sh"

    #ubuntu.vm.provision "shell", path: "sh/x.sh"
    #ubuntu.vm.provision "shell", path: "sh/gnome.sh"

    ubuntu.vm.provision "shell", path: "../common/timezone.sh"
    ubuntu.vm.provision "shell", path: "../common/locale.sh"
    ubuntu.vm.provision "shell", path: "../common/keymap.sh"
  end
end
