# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "arch" do |arch|
    arch.vm.box = "archlinux/archlinux"
    arch.vm.hostname = "arch"
    arch.vm.provider "virtualbox" do |vb|
      vb.name = "arch"
      vb.gui = false
      vb.memory = 1024
      vb.cpus = 2
    end
  end
end
