# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "fedora" do |fedora|
    fedora.vm.box = "iznav/fedora29"
    fedora.vm.hostname = "fedora"
    fedora.vm.synced_folder ".", "/vagrant", disabled: true

    fedora.vm.provider "virtualbox" do |vb|
      vb.name = "fedora"
      vb.gui = false
      vb.memory = 1024
      vb.cpus = 2
    end

    fedora.vm.provider "libvirt" do |lv|
      lv.memory = 1024
      lv.cpus = 2
    end

    fedora.vm.provision "shell", path: "sh/update.sh"

    #fedora.vm.provision "shell", path: "sh/x.sh"
    #fedora.vm.provision "shell", path: "sh/gnome.sh"

    fedora.vm.provision "shell", path: "../common/timezone.sh"
    fedora.vm.provision "shell", path: "../common/locale.sh"
    fedora.vm.provision "shell", path: "../common/keymap.sh"
  end
end
